#Potential Corporate Privacy Violation. Signature ET P2P BitTorrent DHT nodes reply. From: 192.168.21.164:51413, to: 185.21.216.143:58955, protocol: UDP|High|signature_type=ET signature_id=2008583
messages:
  - error: security_detections
    tag: IPS Alert 1
    values:
      alert: ([^.]+)
      source_ip: ((?:[0-9]{1,3}\.){3}[0-9]{1,3})
      destination_ip: ((?:[0-9]{1,3}\.){3}[0-9]{1,3})
      source_port: ([^ ]+)
      destination_port: ([^ ]+)
      protocol: ([^|]+)
      priority: ([^|]+)
      signature: ([^ ]+\s[^ ]+)
    line: 'Potential Corporate Privacy Violation. Signature {alert}. From: {source_ip}:{source_port}, to: {destination_ip}:{destination_port}, protocol: {protocol}|{priority}|{signature}'
    model: NO_MODEL
    mapping:
      variables:
        violations//signatue: signature
        endpoint//source_ip: source_ip
        endpoint//destination_ip: destination_ip
        endpoint//source_port: source_port
        endpoint//destination_port: destination_port
        endpoint//service_type: protocol
        endpoint//traffic_type: alert
      static:
        violations: "corporate_violation"

