#<14>Oct 10 11:39:12 Cloud-Gateway-Ultra Cloud-Gateway-Ultra dpi-flow-stats[1978]: ubnt-dpi-util: pcap dumping rate exceeded: 00:03:ac:59:8c:a3 | 19 total | 8 skipped total | 1 skipped recently | 57.9% dumping success

prefixes:
  - time_format: "%b %d %H:%M:%S"
    values:
      host: ([^ ]+)
      host_details: ([^ ]+)
      message_type: ([^ ]+)
      mon: ([A-Z][a-z]{2})
      day: (\d{1,2})
      time: (\d{2}:\d{2}:\d{2})
      tag: ([^ ]+)
    line: '{mon} {day} {time} {host} {host_details} {tag}: {message_type}: '



