#<14>Oct  8 14:30:14 Cloud-Gateway-Ultra Cloud-Gateway-Ultra dpi-flow-stats[1202]: ubnt-dpi-util: pcap dumping rate exceeded: 1c:ca:e3:7b:66:78 | 1751 total | 957 skipped total | 2 skipped recently | 45.3% dumping success
#"web service not responding and skipped for 1c:ca:e3:7e:2c:be | tries exceeded yes | memory load 0.16"
messages:
  - error: ubnt-dpi-util
    tag: ubnt-dpi-util
    values:
      mac_address: ((?:[0-9A-Fa-f]{2}[:-]){5}(?:[0-9A-Fa-f]{2}))
      valueA: (\d+)
      valueB: (\d+)
      valueC: (\d+)
      valueD: (\d+.\d)
    line: 'pcap dumping rate exceeded: {mac_address} | {valueA} total | {valueB} skipped total | {valueC} skipped recently | {valueD}% dumping success'
    model: NO_MODEL
    mapping:
      variables:
        device_mac: mac_address
        packet//total: valueA
        packet//skipped: valueB
        packet//recently: valueC
        packet//dumping: valueD
      static: {}

        
